#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
bazarr () {

container_reset
# VARIABLES ####################################################################
pgrole="bazarr"
port_inside01="6767"
port_outside01="6767"
traefik_extport="6767"

container_path /etc/localtime /etc/localtime:ro
container_path /pg/data/$pgrole /config
container_path /pg /pg

container_permissions PUID 1000
container_permissions PGID 1000
# IMAGES EXPORT - 1ST IS DEFAULT ###############################################
cat <<- EOF > "/pg/images/$pgrole.images"
linuxserver/bazarr latest
linuxserver/bazarr development
EOF
# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

### END OF FILE ################################################################
EOF
}
