#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
gitea () {

container_reset
# VARIABLES ####################################################################
pgrole="gitea"
port_inside01="3000"
port_outside01="9898"
port_inside02="22" # For SSH
port_outside02="222"
traefik_extport="9898"

container_path /etc/localtime:/etc/localtime:ro
container_path /pg/data/$pgrole /data

container_permissions PUID 1000
container_permissions PGID 1000
# IMAGES EXPORT - 1ST IS DEFAULT ###############################################
cat <<- EOF > "/pg/images/$pgrole.images"
gitea/gitea latest
EOF
# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
          - '${portcheck_add}${port_outside02}:${port_inside02}'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

### END OF FILE ################################################################
EOF
}
