#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
xteve () {

container_reset
# VARIABLES ####################################################################
pgrole="zammad"
port_inside01="34400"
port_outside01="34400"
traefik_extport="34400"

container_path /etc/localtime /etc/localtime:ro
container_path /pg/data/$pgrole/app/tmp /tmp/xteve:rw
container_path /pg/data/$pgrole/app/guide2go /home/xteve/guide2go/conf:rw

container_permissions XTEVE_UID 1000
container_permissions XTEVE_GID 1000
container_permissions XTEVE_BRANCH beta
# IMAGES EXPORT - 1ST IS DEFAULT ###############################################
cat <<- EOF > "/pg/images/$pgrole.images"
dnsforge/xteve latest
EOF
# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

### END OF FILE ################################################################
EOF
}
